name: Temp
on:
  pull_request:
    branches:
      - master
jobs:

  test:
    name: Temp
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: '3.11.2'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.3
      - name: Configure Gradle
        run: |
             cd release/Android
             ./gradlew help
      - name: Spot check
        run: |
             cd release/Android
             ./gradlew check --stacktrace
      - name: Java Protoc
        run: |
             cd release/Android
             mkdir -p grpc_ipfs_lite_pb/src/main/java
             protoc --proto_path=../../ipfs-lite --java_out=./grpc_ipfs_lite_pb/src/main/java/ ../../ipfs-lite/ipfs_lite.proto
      - name: Package Build
        run: |
             cd release/Android
             # sed -i.bak "s/<version>/${VERSION}/g" release/build.gradle
             sed -i.bak "s/<version>/0.0.1-rc0/g" grpc_ipfs_lite_pb/build.gradle
             ./gradlew grpc_ipfs_lite_pb:install
             # ./gradlew pb:bintrayUpload
      - name: Package Upload
        run: |
             cd release/Android
             ./gradlew pb:bintrayUpload
