name: test
on:
  pull_request:
    branches:
      - master
jobs:
  grpc:
    name: grpc-api unit test
    runs-on: textile/builder:1.12.5
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Make test
        run: |
             make test
  android:
    name: android-client build test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          version: '3.11.2'
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.5
      - name: Configure Gradle
        run: |
             cd clients/android
             ./gradlew help
      - name: Check
        run: |
             cd clients/android
             ./gradlew check --stacktrace
      - name: Build
        run: |
             cd clients/android
             sed -i.bak "s/<version>/0.0.1-rc0/g" ipfslite/build.gradle
             ./gradlew ipfslite:install
